name: aws-nuke
on:
  push:
    paths:
      - "trigger.txt"

permissions:
  contents: read

concurrency:
  group: aws-nuke
  cancel-in-progress: false

jobs:
  nuke:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    environment: nuke-approve   # <- 이 환경에 Required reviewers 설정
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token:     ${{ secrets.AWS_SESSION_TOKEN }} # 임시키면 필수
          aws-region: ap-northeast-2

      - name: Who am I?
        run: aws sts get-caller-identity

      - name: Generate aws-nuke config
        run: |
          sed \
            -e "s|\${BLOCKED_ACCOUNT_ID}|${{ secrets.BLOCKED_ACCOUNT_ID }}|g" \
            -e "s|\${TARGET_ACCOUNT_ID}|${{ secrets.TARGET_ACCOUNT_ID }}|g" \
            -e "s|\${KEEP_USER_NAME}|${{ secrets.KEEP_USER_NAME }}|g" \
            -e "s|\${KEEP_ACCESS_KEY_ID}|${{ secrets.KEEP_ACCESS_KEY_ID }}|g" \
            .ops/nuke/config.template.yml > config.yml

      - name: Download aws-nuke v3.56.2
        run: |
          curl -L "https://github.com/ekristen/aws-nuke/releases/download/v3.56.2/aws-nuke-v3.56.2-linux-amd64.tar.gz" -o aws-nuke.tar.gz
          tar -xzf aws-nuke.tar.gz
          sudo mv aws-nuke-v3.56.2-linux-amd64/aws-nuke /usr/local/bin/aws-nuke
          chmod +x /usr/local/bin/aws-nuke
          aws-nuke version

      - name: Nuke (actual)
        run: aws-nuke -c config.yml --no-dry-run --force
