name: aws-nuke

on:
  push:
    paths:
      - "trigger.txt"   # 최상위 trigger.txt 변경 시 실행

permissions:
  contents: read

concurrency:
  group: aws-nuke
  cancel-in-progress: false

jobs:
  nuke:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4

      # AWS 크레덴셜 구성 (Secrets 사용)
      - name: Configure AWS CLI
        run: |
          aws --version || (sudo apt-get update && sudo apt-get install -y awscli)
          mkdir -p ~/.aws
          cat > ~/.aws/credentials <<EOF
          [default]
          aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          EOF
          aws sts get-caller-identity

      # 계정 화이트리스트 확인
      - name: Check allowed account
        run: |
          ACC=$(aws sts get-caller-identity --query Account --output text)
          case "$ACC" in
            ${{ secrets.TARGET_ACCOUNT_ID }}) echo "Allowed account $ACC";;
            *) echo "Blocked account $ACC"; exit 1;;
          esac

      # config.yml 생성 (템플릿 치환)
      - name: Generate aws-nuke config
        run: |
          sed \
            -e "s|\${BLOCKED_ACCOUNT_ID}|${{ secrets.BLOCKED_ACCOUNT_ID }}|g" \
            -e "s|\${TARGET_ACCOUNT_ID}|${{ secrets.TARGET_ACCOUNT_ID }}|g" \
            -e "s|\${KEEP_USER_NAME}|${{ secrets.KEEP_USER_NAME }}|g" \
            -e "s|\${KEEP_ACCESS_KEY_ID}|${{ secrets.KEEP_ACCESS_KEY_ID }}|g" \
            .ops/nuke/config.template.yml > config.yml

      # aws-nuke 다운로드 및 설치
      - name: Download aws-nuke v3.56.2
        run: |
          curl -L "https://github.com/ekristen/aws-nuke/releases/download/v3.56.2/aws-nuke-v3.56.2-linux-amd64.tar.gz" -o aws-nuke.tar.gz
          tar -xzf aws-nuke.tar.gz
          sudo mv aws-nuke-v3.56.2-linux-amd64/aws-nuke /usr/local/bin/aws-nuke
          chmod +x /usr/local/bin/aws-nuke
          aws-nuke version

      # 실제 삭제
      - name: Nuke (actual)
        run: |
          echo "===== Nuke started ====="
          aws-nuke -c config.yml --no-dry-run --force
          echo "===== Nuke completed ====="
