name: aws-nuke

on:
  push:
    paths:
      - "trigger.txt"

permissions:
  contents: read

concurrency:
  group: aws-nuke
  cancel-in-progress: false

jobs:
  nuke:
    runs-on: ubuntu-latest
    timeout-minutes: 100
    environment: nuke-approve
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token:     ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ap-northeast-2

      - name: Identity
        run: aws sts get-caller-identity

      - name: Check allowed account
        run: |
          ACC=$(aws sts get-caller-identity --query Account --output text)
          if [ "$ACC" != "${{ secrets.TARGET_ACCOUNT_ID }}" ]; then
            echo "Blocked account $ACC (expected ${{ secrets.TARGET_ACCOUNT_ID }})"
            exit 1
          fi
          echo "Allowed account $ACC"

      - name: Generate aws-nuke config
        run: |
          sed \
            -e "s|\${BLOCKED_ACCOUNT_ID}|${{ secrets.BLOCKED_ACCOUNT_ID }}|g" \
            -e "s|\${TARGET_ACCOUNT_ID}|${{ secrets.TARGET_ACCOUNT_ID }}|g" \
            -e "s|\${KEEP_USER_NAME}|${{ secrets.KEEP_USER_NAME }}|g" \
            -e "s|\${KEEP_ACCESS_KEY_ID}|${{ secrets.KEEP_ACCESS_KEY_ID }}|g" \
            .ops/nuke/config.template.yml > config.yml

      - name: Download aws-nuke
        run: |
          set -euo pipefail
          curl -L "https://github.com/ekristen/aws-nuke/releases/download/v3.58.0/aws-nuke-v3.58.0-linux-amd64.tar.gz" -o aws-nuke.tar.gz
          tar -xzf aws-nuke.tar.gz
          BIN_NAME=$(tar -tzf aws-nuke.tar.gz | grep -E '^aws-nuke(|-v[0-9].*linux-amd64)$' | head -n1 || true)
          if [ -z "$BIN_NAME" ]; then
            BIN_NAME=$(tar -tzf aws-nuke.tar.gz | grep -E '^aws-nuke[^/]*$' | head -n1 || true)
          fi
          if [ -z "$BIN_NAME" ]; then
            BIN_NAME=$(tar -tzf aws-nuke.tar.gz | grep -v -E '(LICENSE|README|\\.md|\\.txt|\\.pem|\\.sig|/)$' | head -n1)
          fi
          sudo mv "$BIN_NAME" /usr/local/bin/aws-nuke
          sudo chmod +x /usr/local/bin/aws-nuke
          /usr/local/bin/aws-nuke version
      - name: Force color output
        run: echo "FORCE_COLOR=1" >> $GITHUB_ENV
      - name: Nuke
        run: |
          export FORCE_COLOR=1
          /usr/local/bin/aws-nuke nuke -c config.yml --no-dry-run --force
